### PR TITLE
Unity Launch

### PR DESCRIPTION
**Pull request by MaxSchreff**
These commits add the scripts for installing Unity and building Arena-Unity. Now, by running the build-arena-unity.sh script, the Unity simulator should work on any machines without further setup. This works together with the corresponding PR for the unity-simulator branch on arena-rosnav. 

The Arena-Unity implementation was also modified to not use relative paths anymore. I.e. the build can also be started from other locations.

The install script downloads the correct Unity version and puts it into a Arena-Unity-specific location. The build script checks for the Unity Editor and builds the project. The locations of the scripts should not be changed without changing the relative paths within them.

Also, the old sample scene that makes use of the improved graphics from the HDRP is back for better appearance. The Cube now uses a prefab because a texture/shader bug.

### CODE REVIEW

**Comment by ddiaz-0** [comment]
Hey, I'm testing this branch right now, does the script also work with an already (manually) installed Unity Editor? Or should I not call the script in that case?

**Comment by ddiaz-0** [comment]
Update: Tried the script with my existing setup and a fresh Ubuntu installation and in both cases the build fails and I get this error from the log file:
`Library/PackageCache/com.unity.robotics.urdf-importer@8dcc2fa31b/Runtime/AssetHandlers/UrdfAssetPathHandler.cs(23,7): error CS0246: The type or namespace name 'Codice' could not be found (are you missing a using directive or an assembly reference?)` which leads to the a failed build.
On top of that, if Unity Hub is not installed, the script will throw an error that the Unity License should be activated (which is usually done in Unity Hub after you sign in). If you install Unity Hub, sign in and activate a license, this error will not appear anymore.

**Comment by MaxSchreff** [comment]
Thank you for the testing! That are really valuable information. I will try to find some workarounds for that.

**Comment by TheZomb** [comment]
works fine

**Pull request merged**
