### PR TITLE
Training Integration

### PR DESCRIPTION
**Pull request by MaxSchreff**
This PR integrates Arena Unity into the training infrastructure while also updating everything to be compatible with the master of arena rosnav.
There is a corresponding PR in the arena-rosnav repo.

How it can be tested:
- Start arena-rosnav in testing mode:
roslaunch arena_bringup start_arena.launch model:=jackal simulator:=unity
-> Check whether jackal/rgbd/image and jackal/rgbd/depth is published (can be inspected via Rviz)
- Start arena-rosnav in training mode:
roslaunch arena_bringup start_training.launch model:=jackal simulator:=unity headless:=false
and 
in arena-rosnav (poetry shell): python training/scripts/train_agent.py --config unity_rgbd_training_config.yaml

### CODE REVIEW

**Comment by ddiaz-0** [comment]
Hey,
so after doing the setup for your branches and after a quick restart the **testing mode works just fine**, simulation seems to run as intended and depth and rgbd images are being published (was able to see in rviz and via rostopic echo).
rviz screenshot


I'm having the **training mode** running right now and it seems to open the unity editor twice (one of them with all objects and robot spawned, the other one just the walls spawned). Also I'm not sure what the intended behavior is for the robots and the overall scene, cycle resets, etc. , so could you maybe elaborate on that? :eyes:  @MaximilianSchreff

**Comment by MaxSchreff** [comment]
> Hey, so after doing the setup for your branches and after a quick restart the **testing mode works just fine**, simulation seems to run as intended and depth and rgbd images are being published (was able to see in rviz and via rostopic echo). rviz screenshot
> 
> I'm having the **training mode** running right now and it seems to open the unity editor twice (one of them with all objects and robot spawned, the other one just the walls spawned). Also I'm not sure what the intended behavior is for the robots and the overall scene, cycle resets, etc. , so could you maybe elaborate on that? 👀 @MaximilianSchreff



> Hey, so after doing the setup for your branches and after a quick restart the **testing mode works just fine**, simulation seems to run as intended and depth and rgbd images are being published (was able to see in rviz and via rostopic echo). rviz screenshot
> 
> I'm having the **training mode** running right now and it seems to open the unity editor twice (one of them with all objects and robot spawned, the other one just the walls spawned). Also I'm not sure what the intended behavior is for the robots and the overall scene, cycle resets, etc. , so could you maybe elaborate on that? 👀 @MaximilianSchreff

Awesome! The training mode is intended that way. There is an addtional unity environment running because there are periodic evaluations in the environment. I.e. the additional empty unity simulation running is intentional.
About the training, it should just be the simulation resetting again and again after either 500 steps or a collision.

**Comment by ddiaz-0** [comment]
Yes so the robot moves small distances in various directions and after some time the scene resets (new pedestrian/robot positions) and the process starts again. I let it run for around 5-10 minutes but it didn't finish. If that sounds good, then I think we can merge :+1: @MaximilianSchreff

**Comment by MaxSchreff** [comment]
> Yes so the robot moves small distances in various directions and after some time the scene resets (new pedestrian/robot positions) and the process starts again. I let it run for around 5-10 minutes but it didn't finish. If that sounds good, then I think we can merge 👍 @MaximilianSchreff

@ddiaz-0 Yes, this is as expected. You may approve PR now ( ๑‾̀◡‾́) 
But don't merge yet. Will merge once other PRs are through.

**Review by ddiaz-0 — APPROVED** [review]

**Pull request merged**
