### PR TITLE
Character Models and Animations for Pedestrians

### PR DESCRIPTION
**Pull request by ddiaz-0**
This version of the project implements a character model (only male for now) and a basic idle and walking animation for the pedestrians.

This is done by having created a prefab for a male pedestrian in unity (Assets/CharacterModels/Prefabs). This Prefab already has an animator component that handles the animations for this character and a capsule collider object for collision detection (i.e. with the ground or future features). There is already a character model and animation files added for a female character (in Assets/CharacterModel), but it is yet to be standardized into a prefab or used by the PedController spawn function.

The animator component defines the animation that is played in relation to a parameter "velocity" but it doesn't change this parameter on its own, this is done by the PedController.cs script used for moving the pedestrians. This means on top of updating the vector velocity of the (rigid) bodies of the peds, this script now also updates the (forward) velocity parameter (magnitude of the velocity) in the animator component.

As of now, the animation is simply sped up or slowed down in relation to the magnitude of the velocity parameter. In the future, it should be blended between different animations (walking/running) and synchronized to the foot steps on the ground for better immersiveness with a 2D Blend Tree.

### CODE REVIEW

**Comment by MaxSchreff** [comment]
The implementation looks clean! Especially the encapsulation of the animations in the prefab.

The textures don't work for me as well though. Can this be fixed somehow or should we consider other pedestrian models?

**Comment by ddiaz-0** [comment]
Thank you! 👽 Im gonna fix the textures this week or if not possible, find a workaround for it ;)

**Comment by ddiaz-0** [comment]
Short update from my side: The textures should now look good, I reverted them back to HDRP/Lit and HDRP/Hair for the Character Models Body/Hair. I added a new directional sunlight to the scene, so that the objects can actually be presented as they should.
On top of that, the animations should be decent, at least for testing and development. The PedController can now handle up to 6 social states, animations have been added for those too. We are currently waiting for a new state machine, so that the animations can be actually used and optimized further. There will be a new branch for this.
Last but not least, some cleanup and rework of the animator component has been done, and we have a new phone asset :eyes:  Stay tuned for that^^

**Comment by ddiaz-0** [comment]
moving PR to branch in arena-unity

**Pull request closed without merging**
