### PR TITLE
Wall loading

### PR DESCRIPTION
**Pull request by TheZomb**

### CODE REVIEW

**Comment by TheZomb** [comment]
The wall Loading requires using the updated unity simulator in arena-rosnav. Use my Repo (https://github.com/TheZomb/arena-rosnav/tree/unity-simulator) or wait for the PR for the unity-simulator branch to be finished.

**Comment by MaxSchreff** [comment]
The walls are spawned. Good job! 

The coordinate conversion doesn't work though. ROS uses a coordinate format called FLU. The robotics hub provides function for conversion to the unity world reference. (namely .To<FLU>() and .From<FLU>())
They work on Quaternions and on Point messages and converts them to Unity Vector3 and Unity Quaternions. 
Please make sure the walls match with the location of the Peds, Obstacles and the Robot.

There was a small bug in the arena-rosnav unity-simulator branch which I fixed. Make sure to pull again when working on it. 

Another thing is the request message type you defined. 
I think using something like 
"""
Wall[] walls
---
# Definition of Wall message
PointMsg start_point
PointMsg end_point
"""
for the walls would be better than a huge string. The parsing of the string is a lot of unnecessary logic. This would then also allow to use the provided coordinate conversion functions from the robotics hub, since the coordinates are PointMsgs.

**Comment by MaxSchreff** [comment]
@bowski23 
Please take a look at this and look if there is something to be added from you implementation.

**Comment by TheZomb** [comment]
@MaximilianSchreff it's now also proper aligned to other objects in unity and proper msg types. Wall Height can be configured in arena core now instead of Unity

**Comment by MaxSchreff** [comment]
Awsome job!

Adjusted the height of the map to be at 0 so the walls are not floating.
Also, putting all walls into a parent container for walls (just like with peds and obstacles) for better organization especially with bigger maps.

**Pull request merged**
