### PR TITLE
Occupancy Map Generation Tool

### PR DESCRIPTION
**Pull request by bowski23**
A little tool to generate occupancy maps for Unity Scenes.

Checks in a grid for collision, based on a BFS out from the origin like in the non unity part.

### CODE REVIEW

**Comment by MaxSchreff** [comment]
Doesn't affect the simulation. Should this be tested? If yes, how?

**Comment by bowski23** [comment]
Doesn't need to be extensively tested tbh. As long as it lines up with wall generation and rviz it should be fine, which it is for me.

**Comment by MaxSchreff** [comment]
lgtm

**Review by MaxSchreff — APPROVED** [review]
lgtm

**Pull request merged**
